# Application Name
spring.application.name=springboot-restapi

# HTTP Port
server.port=8081

# DB Connection(Oracle 19c) 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=scott
spring.datasource.password=tiger

# Mybatis Mapper
#mybatis.type-aliases-package=com.example.hkms.model
#mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis.config-location=classpath:mybatis/mybatis-config.xml

# Thymeleaf auto refresh
spring.thymeleaf.cache=false

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui